[package]
name = "Spartagram"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12"
tokio = { version = "1", features = ["full"] }
poise = "0.6.1"
dotenv = "0.15"
reqwest="0.12.9"
chrono = "0.4"
